version: '2'

# networks:
#   fabric_ov:
#     external:
#       name: fabric_ov

services:
  # zookeeper0:
  #   image: hyperledger/fabric-zookeeper
  #   environment: 
  #     - GODEBUG=netdns=go
  #     - ZOO_MY_ID=1
  #     - ZOO_PORT=2181
  #     - ZOO_SERVERS=server.1=zookeeper0:2182:2183:participant
  #   ports:
  #     - 2181:2181
  #   container_name: zookeeper0
  #   # networks:
  #   #   - fabric_ov

  # kafka0:
  #   image: hyperledger/fabric-kafka
  #   environment: 
  #     - GODEBUG=netdns=go
  #     - KAFKA_BROKER_ID=0
  #     - KAFKA_DEFAULT_REPLICATION_FACTOR=1
  #     - KAFKA_MESSAGE_MAX_BYTES=103809024
  #     - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
  #     - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181
  #     - KAFKA_MIN_INSYNC_REPLICAS=1
  #     - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
  #   depends_on: 
  #     - zookeeper0
  #   ports: 
  #     - 9092:9092
  #   container_name: kafka0
  #   # networks:
  #   #   - fabric_ov

  orderer0.example.com:
    image: hyperledger/fabric-orderer
    environment: 
      - GODEBUG=netdns=go
      - GOGC=200
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/opt/hyperledger/fabric/msp/crypto-config/ordererOrganizations/orderer.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererOrg
      - ORDERER_GENERAL_LOCALMSPDIR=/opt/hyperledger/fabric/msp/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/opt/hyperledger/fabric/msp/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/opt/hyperledger/fabric/msp/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/opt/hyperledger/fabric/msp/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes: 
      - /opt/go/src/github.com/hyperledger/fabric-test/fabric/common/tools/cryptogen/crypto-config:/opt/hyperledger/fabric/msp/crypto-config
    ports: 
      - 2377:7050
    # depends_on: 
    #   - kafka0
    container_name: orderer0.example.com
    # networks:
    #   - fabric_ov