version: '2'

services:
  ca2:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment: 
      - GODEBUG=netdns=go
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org3
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org3.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/$CA2_SERVER_TLS_KEYFILE
    ports: 
      - 7055:7054
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org3.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/$CA2_SERVER_TLS_KEYFILE -b admin:adminpw -d'
    volumes: 
      - /opt/go/src/github.com/hyperledger/fabric-test/fabric/common/tools/cryptogen/crypto-config/peerOrganizations/org3.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca2



  peer0.org3.example.com:
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_PEER_EVENTS_BUFFERSIZE=1000
      - CORE_PEER_EVENTS_TIMEOUT=100ms 
      - GODEBUG=netdns=go
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=addorg_default
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_ID=peer0.org3.example.com
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.example.com:7051
      - CORE_PEER_MSPCONFIGPATH=/opt/hyperledger/fabric/msp/crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp
      - CORE_PEER_LOCALMSPID=PeerOrg3
      - CORE_PEER_ADDRESS=peer0.org3.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.example.com:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/opt/hyperledger/fabric/msp/crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/opt/hyperledger/fabric/msp/crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/hyperledger/fabric/msp/crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/ca.crt
    #   - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    #   - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
    # depends_on:
    #   - couchdb2
    volumes: 
      - /var/run/:/host/var/run/
      - /opt/go/src/github.com/hyperledger/fabric-test/fabric/common/tools/cryptogen/crypto-config:/opt/hyperledger/fabric/msp/crypto-config
      - /data/ledgers_backup/peer0.org3.example.com:/var/hyperledger/production
    ports: 
      - 7065:7051
      - 6055:7053
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    container_name: peer0.org3.example.com
    extra_hosts:
      - "orderer0.example.com:172.16.50.153"
      - "orderer1.example.com:172.16.50.153"
      - "orderer2.example.com:172.16.50.153"
      - "peer0.org1.example.com:172.16.50.151"

  peer1.org3.example.com:
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment: 
      - CORE_PEER_EVENTS_BUFFERSIZE=1000
      - CORE_PEER_EVENTS_TIMEOUT=100ms 
      - GODEBUG=netdns=go
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=addorg_default
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_ID=peer1.org3.example.com
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.example.com:7051
      - CORE_PEER_MSPCONFIGPATH=/opt/hyperledger/fabric/msp/crypto-config/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/msp
      - CORE_PEER_LOCALMSPID=Peerorg3
      - CORE_PEER_ADDRESS=peer1.org3.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.example.com:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/opt/hyperledger/fabric/msp/crypto-config/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/opt/hyperledger/fabric/msp/crypto-config/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/hyperledger/fabric/msp/crypto-config/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/tls/ca.crt
    #   - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    #   - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
    # depends_on:
    #   - couchdb3
    volumes: 
      - /var/run/:/host/var/run/
      - /opt/go/src/github.com/hyperledger/fabric-test/fabric/common/tools/cryptogen/crypto-config:/opt/hyperledger/fabric/msp/crypto-config
      - /data/ledgers_backup/peer1.org3.example.com:/var/hyperledger/production
    ports: 
      - 7066:7051
      - 6056:7053
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    container_name: peer1.org3.example.com
    extra_hosts:
      - "orderer0.example.com:172.16.50.153"
      - "orderer1.example.com:172.16.50.153"
      - "orderer2.example.com:172.16.50.153"

  # couchdb2:
  #   image: hyperledger/fabric-couchdb:$SUPPORT_TAG
  #   environment:
  #     - ERL_MAX_PORTS=4096
  #   ports: 
  #     - 5986:5984
  #   container_name: couchdb2

  # couchdb3:
  #   image: hyperledger/fabric-couchdb:$SUPPORT_TAG
  #   environment:
  #     - ERL_MAX_PORTS=4096
  #   ports: 
  #     - 5987:5984
  #   container_name: couchdb3


  Org3cli:
    container_name: Org3cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GODEBUG=netdns=go
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # - CORE_LOGGING_LEVEL=INFO
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=Org3cli
      - CORE_PEER_ADDRESS=peer0.org3.example.com:7051
      - CORE_PEER_LOCALMSPID=Peerorg3
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/opt/hyperledger/fabric/msp/crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/opt/hyperledger/fabric/msp/crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/hyperledger/fabric/msp/crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/hyperledger/fabric/msp/crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - /opt/go/src/github.com/hyperledger/fabric-test/fabric/common/tools/cryptogen/crypto-config/:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./../chaincode/:/opt/gopath/src/github.com/chaincode
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer0.org3.example.com
      - peer1.org3.example.com
    extra_hosts:
      - "orderer0.example.com:172.16.50.153"
      - "orderer1.example.com:172.16.50.153"
      - "orderer2.example.com:172.16.50.153"
      - "peer0.org1.example.com:172.16.50.151"
      - "peer0.org2.example.com:172.16.50.153"


