version: '2'

services:

  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - GODEBUG=netdns=go
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/db931990f9dcd0f7d5fcbd4564a0fbac33ce4dab64f6194dcfd37d49fb553095_sk
    ports: 
      - 7054:7054
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/db931990f9dcd0f7d5fcbd4564a0fbac33ce4dab64f6194dcfd37d49fb553095_sk -b admin:adminpw -d'
    volumes: 
      - /opt/go/src/github.com/hyperledger/fabric-test/fabric/common/tools/cryptogen/crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca0



  peer0.org1.example.com:
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment: 
      # - CORE_metrics_enabled=true
      # - CORE_METRICS_REPORTER=prom
      # - CORE_metrics_promReporter_listenAddress=172.16.50.151:8080
      # - CORE_METRICS_STATSDREPORTER_ADDRESS=0.0.0.0:8125
      # - CORE_METRICS_statsdreporter_flushBytes=1432
      # - CORE_METRICS_statsdreporter_flushInterval=2s
      - CORE_PEER_EVENTS_BUFFERSIZE=1000
      - CORE_PEER_EVENTS_TIMEOUT=100ms 
      - GODEBUG=netdns=go
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=couchdb_default
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_MSPCONFIGPATH=/opt/hyperledger/fabric/msp/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp
      - CORE_PEER_LOCALMSPID=PeerOrg1
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/opt/hyperledger/fabric/msp/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/opt/hyperledger/fabric/msp/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/hyperledger/fabric/msp/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
    depends_on:
      - couchdb0
    volumes: 
      - /var/run/:/host/var/run/
      - /opt/go/src/github.com/hyperledger/fabric-test/fabric/common/tools/cryptogen/crypto-config:/opt/hyperledger/fabric/msp/crypto-config
      - /data/ledgers_backup/peer0.org1.example.com:/var/hyperledger/production
    ports: 
      - 7061:7051
      - 6051:7053
      - 6060:6060
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    container_name: peer0.org1.example.com
    extra_hosts:
      - "orderer0.example.com:172.16.50.153"
      - "orderer1.example.com:172.16.50.153"
      - "orderer2.example.com:172.16.50.153"
      - "peer0.org2.example.com:172.16.50.153"

  peer1.org1.example.com:
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment: 
      - CORE_PEER_EVENTS_BUFFERSIZE=1000
      - CORE_PEER_EVENTS_TIMEOUT=100ms 
      - GODEBUG=netdns=go
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=couchdb_default
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_ID=peer1.org1.example.com
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
      - CORE_PEER_MSPCONFIGPATH=/opt/hyperledger/fabric/msp/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp
      - CORE_PEER_LOCALMSPID=PeerOrg1
      - CORE_PEER_ADDRESS=peer1.org1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.example.com:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/opt/hyperledger/fabric/msp/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/opt/hyperledger/fabric/msp/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/hyperledger/fabric/msp/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/ca.crt
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5985
    depends_on:
      - couchdb1
    volumes: 
      - /var/run/:/host/var/run/
      - /opt/go/src/github.com/hyperledger/fabric-test/fabric/common/tools/cryptogen/crypto-config:/opt/hyperledger/fabric/msp/crypto-config
      - /data/ledgers_backup/peer1.org1.example.com:/var/hyperledger/production
    ports: 
      - 7062:7051
      - 6052:7053
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    container_name: peer1.org1.example.com
    extra_hosts:
      - "orderer0.example.com:172.16.50.153"
      - "orderer1.example.com:172.16.50.153"
      - "orderer2.example.com:172.16.50.153"

  couchdb0:
    image: hyperledger/fabric-couchdb
    ports: 
      - 5984:5984
    container_name: couchdb0

  couchdb1:
    image: hyperledger/fabric-couchdb
    ports: 
      - 5985:5984
    container_name: couchdb1

